
import java.awt.event.KeyEvent;
import javafx.scene.paint.Color;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Arango Abello
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Sudoku
     */
    public javax.swing.JButton[][] botones = new javax.swing.JButton[9][9];
    public Sudoku sudoku;
    
    public Ventana() {
        initComponents();
//        cargarBotones();
        sudoku=new Sudoku();
//        agregarListeners();
        this.setLocationRelativeTo(null);
//        panelSudoku1.addKeyListener(panelSudoku1);
        jButton3.doClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSudoku1 = panelSudoku1 = new PanelSudoku(this);
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sudoku");
        setMaximumSize(new java.awt.Dimension(700, 800));
        setMinimumSize(new java.awt.Dimension(190, 250));

        panelSudoku1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelSudoku1Layout = new javax.swing.GroupLayout(panelSudoku1);
        panelSudoku1.setLayout(panelSudoku1Layout);
        panelSudoku1Layout.setHorizontalGroup(
            panelSudoku1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelSudoku1Layout.setVerticalGroup(
            panelSudoku1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/resolver.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cargar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sudokus de prueba ...", "Sudoku fácil", "Sudoku medio", "Sudoku difícil" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 127, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelSudoku1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(panelSudoku1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void agregarListeners(){
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones.length; j++) {
                botones[i][j].addFocusListener(new FocusAdapter(botones[i][j]));
                botones[i][j].addKeyListener(new KeyAdapter(botones[i][j]));
            }
        }
        
    }
    
    public class FocusAdapter extends java.awt.event.FocusAdapter{
        
        JButton boton;

        public FocusAdapter(JButton boton) {
            this.boton = boton;
        }

       @Override
       public void focusLost(java.awt.event.FocusEvent evt) {
            cargarValor(boton);
       }
   }
    
    public class KeyAdapter extends java.awt.event.KeyAdapter{
        JButton boton;

        public KeyAdapter(JButton boton) {
            this.boton = boton;
        }
        @Override
         public void keyReleased(java.awt.event.KeyEvent evt) {
            teclaOprimida(boton,evt);
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        sudoku.valores=new int[9][9];
        panelSudoku1.cargando=true;
        panelSudoku1.finalesCargado=false;
        panelSudoku1.repaint();
        panelSudoku1.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void teclaOprimida(JButton tecla,java.awt.event.KeyEvent evt){
        if(evt.getKeyCode()!=KeyEvent.VK_1&&evt.getKeyCode()!=KeyEvent.VK_2&&evt.getKeyCode()!=KeyEvent.VK_3&&evt.getKeyCode()!=KeyEvent.VK_4&&evt.getKeyCode()!=KeyEvent.VK_5&&evt.getKeyCode()!=KeyEvent.VK_6&&evt.getKeyCode()!=KeyEvent.VK_7&&evt.getKeyCode()!=KeyEvent.VK_8&&evt.getKeyCode()!=KeyEvent.VK_9&&evt.getKeyCode()!=KeyEvent.VK_NUMPAD1&&evt.getKeyCode()!=KeyEvent.VK_NUMPAD2&&evt.getKeyCode()!=KeyEvent.VK_NUMPAD3&&evt.getKeyCode()!=KeyEvent.VK_NUMPAD4&&evt.getKeyCode()!=KeyEvent.VK_NUMPAD5&&evt.getKeyCode()!=KeyEvent.VK_NUMPAD6&&evt.getKeyCode()!=KeyEvent.VK_NUMPAD7&&evt.getKeyCode()!=KeyEvent.VK_NUMPAD8&&evt.getKeyCode()!=KeyEvent.VK_NUMPAD9){
            return;
        }
        tecla.setText(""+KeyEvent.getKeyText(evt.getKeyCode()).charAt(KeyEvent.getKeyText(evt.getKeyCode()).length()-1));
    }
    
    public void cargarValor(JButton boton){
        if (boton.getText().equals("")) {
            return;
        }
        for (int i = 0; i < botones.length; i++) {
            for (int j = 0; j < botones.length; j++) {
                if (botones[i][j]==boton) {
                    sudoku.valores[i][j]=Integer.valueOf(boton.getText());
                }
            }
        }
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelSudoku1.cargando=true;
        panelSudoku1.valoresFinales = sudoku.aplicador();
        panelSudoku1.finalesCargado=true;
        panelSudoku1.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setSize(569, 660);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        int seleccion=jComboBox1.getSelectedIndex();
        if (seleccion==1) {            
            sudoku.valores=panelSudoku1.sudokuFacil;
        }
        if (seleccion==2) {
            sudoku.valores=panelSudoku1.sudokuMedio;
        }
        if (seleccion==3) {
            sudoku.valores=panelSudoku1.sudokuDificil;
        }
        panelSudoku1.finalesCargado=false;
        panelSudoku1.repaint();
    }//GEN-LAST:event_jComboBox1ItemStateChanged
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JPanel jPanel2;
    private PanelSudoku panelSudoku1;
    // End of variables declaration//GEN-END:variables

   
}

